version: 1

update_configs:

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: auto
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
