name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mock-api:
        image: firstclasspostcodes/mock:latest
        env:
          PORT: 3000
        ports:
          - '3000:3000'
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build & Test
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint
        run: |
          pipenv run flake8 .
      - name: Test
        run: |
          pipenv run pytest
      - name: Integration Tests
        run: |
          pipenv run pytest tests/integration*.py
        env:
          API_URL: http://localhost:3000
          API_KEY: '111111111111'

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build & Test
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        uses: AlphaMycelium/psr-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          pypi_username: ${{secrets.PYPI_USERNAME}}
          pypi_password: ${{secrets.PYPI_PASSWORD}}